[package]
name = "ratatui-macros"
version = "0.7.0-alpha.0"
edition = "2021"
authors = ["The Ratatui Developers"]
description = "Macros for Ratatui"
license = "MIT"                                              # or any other appropriate license
repository = "https://github.com/ratatui-org/ratatui-macros"
documentation = "https://docs.rs/ratatui-macros"
keywords = ["ratatui", "macros", "tui", "ui"]
categories = ["command-line-interface"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui-core = "0.1.0-alpha.3"
ratatui-widgets = "0.3.0-alpha.2"

[dev-dependencies]
trybuild = { version = "1.0.103", features = ["diff"] }
cargo-husky = { version = "1.5.0", features = ["user-hooks"] }
